### ISSUE TITLE
Function to plot all modules

### ISSUE THREAD

**Issue by joshua-d-campbell** [campbio/celda#35]
Right now only 1 module can be plotted at a time in moduleHeatmap. It would be nice to have a function that systematically plotted each module in a single file so users can quickly flip through and evaluate them. Here is a simple "for" loop where "m" is a celda_G or celda_CG model:  

pdf("modules.pdf"); for(i in 1:m@params$L) {moduleHeatmap(pbmc, m, i)}; dev.off() 

However this file can be very big depending on the number of modules. Is there a way to rasterize the heatmaps so they take up less size? Also it would be cool to plot two heatmaps on each page for a module: 1) One with all cells to give the "big" picture and 2) one that has that sets "top.cells" to like 100 to view the module at the extremes.

**Comment by definitelysean** [comment]
I think that some refactor as part of this issue is warranted. The approach I would take would be this:

1. Refactor heatmap functions to use ComplexHeatmap. This would be because this package has a [use_raster functionality](https://github.com/jokergoo/ComplexHeatmap/search?q=use_raster&unscoped_q=use_raster) built in.
2. Incorporate gridExtra, so we could use [grid.arrange() to lay these heatmaps out in a grid](https://support.bioconductor.org/p/87318/).

@zhewa  Let me know if you think this is a good approach, or if there's possibly an easier way to do this.

**Comment by zhewa** [comment]
@definitelysean Option 1 seems like a good way to do this.

**Comment by zhewa** [comment]
Fixed in #298
